#!/bin/sh
#set -x
echo "❗❕ pre-commit"
username=$(git config user.name)
username2=""
prefix="Muhammad"
post1="icm"
post2="ICM"
post3="Icm"
post4="iCM"

if [[ $username = *" "* ]]; then
    arr=(${username// / })
    for val in "${arr[@]}"; do
        username2+="$val"
    done
else
    username2+="$username"
fi
username2="${username2//-/}"
username2="${username2//_/}"
username2=${username2//[[:digit:]]/}
username2="${username2//./}"
username2=${username2#"$prefix"}
username2="${username2%$post1}"
username2="${username2%$post2}"
username2="${username2%$post3}"
username2="${username2%$post4}"
#-------------------------------------------------------------------------
day=`date +%d`
month=`date +%m`
BRANCH_NAME=$(git branch --show-current)
if [ $BRANCH_NAME ]; then
    if [[ $BRANCH_NAME != @(dev|DEV|Dev|master|Master|qa|QA|Qa) ]]; then
        array=(${BRANCH_NAME//_/ })
        if (( ${#array[@]} == 1 ))
        then
            if [[ $BRANCH_NAME != ?(-)+([0-9]) ]]; then
                echo "🚫 '${array[0]}' is not Jira Ticket Number (Integer).";
                exit 1
            fi
            count=0
            new_name="${array[0]}_${username2}_${month}${day}"
            old_name=$new_name
            while [ true ]
            do
                res=$(git ls-remote --exit-code --heads origin $new_name)
                if [[ $res ]]; then
                    echo "Branch exists '${new_name}' ✔";
                    count=$(( $count + 1 ))
                    new_name="${old_name}_${count}"
                else
                    $(git branch -m $new_name)
                    echo "✔ Branch '$new_name' has been created successfully."
                    break
                fi
            done
        fi
    fi
fi
#-------------------------------------------------------------------------
