#!/bin/sh
#set -x
echo "❗❕ pre-push"
BRANCH_NAME=$(git branch --show-current)
if [ $BRANCH_NAME ]; then
    if [[ $BRANCH_NAME != @(dev|DEV|Dev|master|Master|qa|QA|Qa) ]]; then
        array=(${BRANCH_NAME//_/ })
        res=$(git ls-remote --exit-code --heads origin $BRANCH_NAME)
        if [[ $res ]]; then
            echo "Branch exists ✔";
        else
            if (( ${#array[@]} == 1 ))
            then
                echo "🚫 Please commit some changes and then push.";
                exit 1
            fi
        fi
    fi
fi