# For auto generating this yaml file for .NET project run these command sequencely
#dotnet new workflow --search
#dotnet new --install TimHeuer.GitHubActions.Templates
#dotnet new workflow

name: Continues Integration and Deployment

on:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: '6.0.x'
  AZURE_WEB_APP_NAME: rainers-first-webapp

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code 🚓
        uses: actions/checkout@v3
      
      - name: Make changes
        run: echo "Hello, World!" >> hello.txt

      - name: Commit and push
        run: |
          git config --global user.name 'shahrukhkhan532'
          git config --global user.email 'khanxhahrukh@gmail.com'
          
          git remote set-url origin https://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@github.com/shahrukhkhan532/NET6.git
          git add -A
          git commit -m "Automated commit from GitHub Actions"
          git push
