name: Scheduled Workflow

on:
  schedule:
    - cron: '* * * * *'

jobs:
  scheduled-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run scheduled task
      run: |
        echo "This is your scheduled task, customize it as needed."