name:
  First Cron Job
 
  # Controls when the workflow will run
on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/5 * * * *"
 
      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
          curl -X POST -H "Content-Type: application/json" -d '{"Name":"First Cron Job"}' https://webhook.site/b290ab70-c9cf-4c22-829b-781a8dccd961
