name: Run Sql Script 📜

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        type: string
    secrets:
      INSTANCE:
        required: true
      DBNAME:
        required: true
      UID:
        required: true
      PASSWORD:
        required: true

jobs:
  RUN-SQL-SCRIPTS:
    runs-on:
      - self-hosted
      - label-test
    steps:
      - name: Check Out Code 🚓
        uses: actions/checkout@v3

      - name: Run SQL Scripts 📜
        shell: PowerShell
        run: |
          Write-Output ("THIS IS BRANCH - " + $branch)
          $scriptPath = ((Get-Location) + "\DB Script")
          Write-Output $scriptPath

          $instance = "${{ secrets.INSTANCE }}"
          $DbName = "${{ secrets.DBNAME }}"
          $UID = "${{ secrets.UID }}"
          $Password = "${{ secrets.PASSWORD }}"
          $OutputSQLFilePath = ($scriptPath + (Get-Date -UFormat "%d-%m-%Y") + ".log")

          $files = Get-ChildItem -Path $scriptPath -Recurse -Include *.sql
          foreach ($file in $files) 
          {
              Invoke-Sqlcmd -ServerInstance $instance -Database $DbName -Username $UID -Password $Password -InputFile $file
              if(!($?)){
                ($file.Name + " Contains Errors 👇`n") >> $OutputSQLFilePath
                ($Error[0].Exception.Message + "`n") >> $OutputSQLFilePath
              }else{
                ($file.Name + " Successfully Executed ✔.`n") >> $OutputSQLFilePath
              }
          }
          $github_URL = "https://api.github.com/users/" + "${{ github.actor }}"
          $User = Invoke-RestMethod -Method Get -Uri $github_URL
          $username = ""
          if([string]::IsNullOrEmpty($User.name)){
              $username = $User.login
          }else{
              $username = $User.name
          }
          $title = "Scripts executed on " + "${{ github.ref_name }}" + "by " + $username
          $message = (Get-Content $OutputSQLFilePath)
          $param = @{
              Uri = "https://jsonplaceholder.typicode.com/posts"
              Method = "POST"
              Body = @{
                  id = 1
                  title = $title
                  body = $message
                  text = $message
              } | ConvertTo-Json
              ContentType = 'application/json'
          }
          Invoke-RestMethod @param